In [23]:
import pandas as pd
customer_happiness=pd.read_csv(r"C:\Users\OYEKUNLE DAVID O\Documents\Apziva\ACME-HappinessSurvey2020.csv")

In [27]:
customer_happiness.loc[customer_happiness['Y']==1]

     Y  X1  X2  X3  X4  X5  X6
2    1   5   3   3   3   3   5
5    1   5   5   3   5   5   5
7    1   5   4   4   4   4   5
12   1   5   2   4   5   5   5
15   1   3   2   4   3   4   4
..  ..  ..  ..  ..  ..  ..  ..
118  1   4   3   3   4   4   4
119  1   5   5   1   1   5   1
121  1   5   2   3   4   4   3
122  1   5   2   3   4   2   5
123  1   5   3   3   4   4   5

[69 rows x 7 columns]

In [11]:
customer_happiness.loc[customer_happiness['Y']==1].shape

(69, 7)

In [4]:
customer_happiness.loc[(customer_happiness['Y']==1) & (customer_happiness['X1']>=3)]

     Y  X1  X2  X3  X4  X5  X6
2    1   5   3   3   3   3   5
5    1   5   5   3   5   5   5
7    1   5   4   4   4   4   5
12   1   5   2   4   5   5   5
15   1   3   2   4   3   4   4
..  ..  ..  ..  ..  ..  ..  ..
118  1   4   3   3   4   4   4
119  1   5   5   1   1   5   1
121  1   5   2   3   4   4   3
122  1   5   2   3   4   2   5
123  1   5   3   3   4   4   5

[69 rows x 7 columns]

In [12]:
customer_happiness.loc[(customer_happiness['Y']==1) & (customer_happiness['X1']>=3)].shape

(69, 7)

In [5]:
customer_happiness.loc[(customer_happiness['Y']==1) & (customer_happiness['X2']>=3)]

     Y  X1  X2  X3  X4  X5  X6
2    1   5   3   3   3   3   5
5    1   5   5   3   5   5   5
7    1   5   4   4   4   4   5
24   1   4   3   3   3   3   4
26   1   3   3   3   5   5   5
27   1   3   3   1   3   3   4
28   1   3   3   1   3   3   4
29   1   5   3   3   3   5   3
36   1   5   3   4   3   4   5
37   1   5   3   4   3   4   5
39   1   4   4   3   4   2   4
45   1   5   3   4   4   4   5
46   1   5   3   3   4   4   5
54   1   4   3   2   4   3   4
55   1   4   3   2   4   3   4
58   1   5   3   5   5   4   5
69   1   5   4   5   5   5   5
70   1   4   3   3   4   3   4
72   1   4   3   3   4   2   4
79   1   5   5   5   5   5   5
80   1   4   3   2   4   4   4
83   1   5   3   2   4   4   4
86   1   5   3   3   3   5   5
92   1   5   4   5   5   5   4
93   1   5   4   4   4   4   5
95   1   5   5   5   5   5   5
97   1   5   4   5   4   5   4
101  1   5   3   4   3   4   3
103  1   4   3   4   4   3   4
109  1   5   3   4   4   4   4
116  1   3   4   4   5   1   3
118  1   4   3   3   4   4   4
119  1   5   5   1   1   5   1
123  1   5   3   3   4   4   5

In [13]:
customer_happiness.loc[(customer_happiness['Y']==1) & (customer_happiness['X2']>=3)].shape

(34, 7)

In [6]:
customer_happiness.loc[(customer_happiness['Y']==1) & (customer_happiness['X3']>=3)]

     Y  X1  X2  X3  X4  X5  X6
2    1   5   3   3   3   3   5
5    1   5   5   3   5   5   5
7    1   5   4   4   4   4   5
12   1   5   2   4   5   5   5
15   1   3   2   4   3   4   4
17   1   5   1   4   3   4   5
20   1   4   2   3   3   4   4
24   1   4   3   3   3   3   4
26   1   3   3   3   5   5   5
29   1   5   3   3   3   5   3
32   1   3   2   4   4   4   5
33   1   3   2   4   4   4   5
34   1   4   1   3   1   1   4
36   1   5   3   4   3   4   5
37   1   5   3   4   3   4   5
38   1   5   2   3   3   2   5
39   1   4   4   3   4   2   4
41   1   4   2   4   3   2   4
45   1   5   3   4   4   4   5
46   1   5   3   3   4   4   5
48   1   5   2   5   5   5   3
49   1   5   1   3   3   4   4
50   1   5   1   3   3   4   4
51   1   5   1   3   3   4   4
52   1   5   2   4   3   4   5
53   1   5   2   4   3   4   5
58   1   5   3   5   5   4   5
59   1   5   2   4   2   2   4
61   1   5   2   4   4   5   5
62   1   5   2   4   4   5   5
64   1   4   1   3   4   4   4
65   1   4   1   3   4   4   4
68   1   5   1   5   5   5   5
69   1   5   4   5   5   5   5
70   1   4   3   3   4   3   4
72   1   4   3   3   4   2   4
74   1   5   2   5   5   5   5
77   1   5   2   3   5   5   5
79   1   5   5   5   5   5   5
82   1   4   2   4   4   4   4
85   1   5   2   3   4   4   5
86   1   5   3   3   3   5   5
91   1   5   1   3   4   5   5
92   1   5   4   5   5   5   4
93   1   5   4   4   4   4   5
95   1   5   5   5   5   5   5
97   1   5   4   5   4   5   4
98   1   4   2   3   4   3   3
101  1   5   3   4   3   4   3
103  1   4   3   4   4   3   4
105  1   5   1   4   3   5   5
106  1   5   1   5   3   5   5
109  1   5   3   4   4   4   4
116  1   3   4   4   5   1   3
117  1   5   1   5   5   5   5
118  1   4   3   3   4   4   4
121  1   5   2   3   4   4   3
122  1   5   2   3   4   2   5
123  1   5   3   3   4   4   5

In [14]:
customer_happiness.loc[(customer_happiness['Y']==1) & (customer_happiness['X3']>=3)].shape

(59, 7)

In [7]:
customer_happiness.loc[(customer_happiness['Y']==1) & (customer_happiness['X4']>=3)]

     Y  X1  X2  X3  X4  X5  X6
2    1   5   3   3   3   3   5
5    1   5   5   3   5   5   5
7    1   5   4   4   4   4   5
12   1   5   2   4   5   5   5
15   1   3   2   4   3   4   4
..  ..  ..  ..  ..  ..  ..  ..
117  1   5   1   5   5   5   5
118  1   4   3   3   4   4   4
121  1   5   2   3   4   4   3
122  1   5   2   3   4   2   5
123  1   5   3   3   4   4   5

[66 rows x 7 columns]

In [15]:
customer_happiness.loc[(customer_happiness['Y']==1) & (customer_happiness['X4']>=3)].shape

(66, 7)

In [8]:
customer_happiness.loc[(customer_happiness['Y']==1) & (customer_happiness['X5']>=3)]

     Y  X1  X2  X3  X4  X5  X6
2    1   5   3   3   3   3   5
5    1   5   5   3   5   5   5
7    1   5   4   4   4   4   5
12   1   5   2   4   5   5   5
15   1   3   2   4   3   4   4
17   1   5   1   4   3   4   5
20   1   4   2   3   3   4   4
24   1   4   3   3   3   3   4
26   1   3   3   3   5   5   5
27   1   3   3   1   3   3   4
28   1   3   3   1   3   3   4
29   1   5   3   3   3   5   3
32   1   3   2   4   4   4   5
33   1   3   2   4   4   4   5
36   1   5   3   4   3   4   5
37   1   5   3   4   3   4   5
44   1   3   1   2   4   3   5
45   1   5   3   4   4   4   5
46   1   5   3   3   4   4   5
48   1   5   2   5   5   5   3
49   1   5   1   3   3   4   4
50   1   5   1   3   3   4   4
51   1   5   1   3   3   4   4
52   1   5   2   4   3   4   5
53   1   5   2   4   3   4   5
54   1   4   3   2   4   3   4
55   1   4   3   2   4   3   4
58   1   5   3   5   5   4   5
61   1   5   2   4   4   5   5
62   1   5   2   4   4   5   5
64   1   4   1   3   4   4   4
65   1   4   1   3   4   4   4
68   1   5   1   5   5   5   5
69   1   5   4   5   5   5   5
70   1   4   3   3   4   3   4
74   1   5   2   5   5   5   5
77   1   5   2   3   5   5   5
79   1   5   5   5   5   5   5
80   1   4   3   2   4   4   4
82   1   4   2   4   4   4   4
83   1   5   3   2   4   4   4
85   1   5   2   3   4   4   5
86   1   5   3   3   3   5   5
91   1   5   1   3   4   5   5
92   1   5   4   5   5   5   4
93   1   5   4   4   4   4   5
95   1   5   5   5   5   5   5
97   1   5   4   5   4   5   4
98   1   4   2   3   4   3   3
100  1   5   2   2   4   5   5
101  1   5   3   4   3   4   3
103  1   4   3   4   4   3   4
105  1   5   1   4   3   5   5
106  1   5   1   5   3   5   5
109  1   5   3   4   4   4   4
117  1   5   1   5   5   5   5
118  1   4   3   3   4   4   4
119  1   5   5   1   1   5   1
121  1   5   2   3   4   4   3
123  1   5   3   3   4   4   5

In [16]:
customer_happiness.loc[(customer_happiness['Y']==1) & (customer_happiness['X5']>=3)].shape

(60, 7)

In [9]:
customer_happiness.loc[(customer_happiness['Y']==1) & (customer_happiness['X6']>=3)]

     Y  X1  X2  X3  X4  X5  X6
2    1   5   3   3   3   3   5
5    1   5   5   3   5   5   5
7    1   5   4   4   4   4   5
12   1   5   2   4   5   5   5
15   1   3   2   4   3   4   4
..  ..  ..  ..  ..  ..  ..  ..
117  1   5   1   5   5   5   5
118  1   4   3   3   4   4   4
121  1   5   2   3   4   4   3
122  1   5   2   3   4   2   5
123  1   5   3   3   4   4   5

[68 rows x 7 columns]

In [17]:
customer_happiness.loc[(customer_happiness['Y']==1) & (customer_happiness['X6']>=3)].shape

(68, 7)